export const std = { "std/num/abs": Math.abs,
  "std/num/acos": Math.acos,
  "std/num/acosh": Math.acosh,
  "std/num/asin": Math.asin,
  "std/num/asinh": Math.asinh,
  "std/num/atan": Math.atan,
  "std/num/atan2": Math.atan2,
  "std/num/atanh": Math.atanh,
  "std/num/cbrt": Math.cbrt,
  "std/num/ceil": Math.ceil,
  "std/num/clz32": Math.clz32,
  "std/num/cos": Math.cos,
  "std/num/cosh": Math.cosh,
  "std/num/div": (x: number, y: number) => x / y,
  "std/num/exp": Math.exp,
  "std/num/expm1": Math.expm1,
  "std/num/floor": Math.floor,
  "std/num/fround": Math.fround,
  "std/num/hypot": Math.hypot,
  "std/num/imul": Math.imul,
  "std/num/log": Math.log,
  "std/num/log10": Math.log10,
  "std/num/log1p": Math.log1p,
  "std/num/log2": Math.log2,
  "std/num/max": Math.max,
  "std/num/min": Math.min,
  "std/num/mul": (x: number, y: number) => x * y,
  "std/num/pow": Math.pow,
  "std/num/random": Math.random,
  "std/num/round": Math.round,
  "std/num/sign": Math.sign,
  "std/num/sin": Math.sin,
  "std/num/sinh": Math.sinh,
  "std/num/sqrt": Math.sqrt,
  "std/num/sub": (x: number, y: number) => x - y,
  "std/num/sum": (x: number, y: number) => x + y,
  "std/num/tan": Math.tan,
  "std/num/tanh": Math.tanh,
  "std/num/trunc": Math.trunc}