# @info
# main & pull_request jobs cannot de-dupe their workflow configuration :(
# https://github.community/t5/GitHub-Actions/Start-a-workflow-from-another-workflow/td-p/37586
name: main
on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    env:
      NEXT_PUBLIC_BASE_PATH: /programming-language-selector
    runs-on: ubuntu-latest
    steps:
      # https://github.com/JamesIves/github-pages-deploy-action#getting-started-airplane
      - name: checkout 🛎️
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          persist-credentials: false
      - name: Install pnpm
        run: npm install -g pnpm@8.7.1
      - uses: actions/setup-node@v4
        with:
          node-version: 20.3.0
          cache: "pnpm"
      - name: Install and Test
        run: |
          pnpm install
          pnpm format:check
          pnpm build
          cd apps/ui && pnpm run build-storybook
